name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # Job 1: Code Quality Checks
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: TypeScript type check
        run: npm run build

      - name: Check for build artifacts
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not created"
            exit 1
          fi
          echo "Build successful: dist directory exists"

  # Job 2: Test (placeholder for when you add tests)
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: true  # Allow to pass even if no tests yet

      - name: Test placeholder notice
        run: |
          echo "⚠️  No tests implemented yet"
          echo "Add tests to improve code quality and catch bugs early"

  # Job 3: Wrangler Validation
  validate-wrangler:
    name: Validate Wrangler Config
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Validate wrangler.toml
        run: |
          if [ ! -f "wrangler.toml" ]; then
            echo "Error: wrangler.toml not found"
            exit 1
          fi
          echo "✓ wrangler.toml exists"

      - name: Check TypeScript compilation
        run: npx wrangler types
        continue-on-error: true

  # Job 4: Security Audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Check for secrets in code
        run: |
          if grep -r "CLOUDFLARE_API_TOKEN\|API_KEY\|SECRET" src/ --exclude-dir=node_modules; then
            echo "⚠️  Warning: Potential secrets found in source code"
            exit 1
          else
            echo "✓ No obvious secrets found in source code"
          fi

  # Summary job
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [quality, test, validate-wrangler, security]
    if: always()

    steps:
      - name: Check all jobs
        run: |
          echo "CI Pipeline Complete!"
          echo "Quality: ${{ needs.quality.result }}"
          echo "Tests: ${{ needs.test.result }}"
          echo "Wrangler: ${{ needs.validate-wrangler.result }}"
          echo "Security: ${{ needs.security.result }}"
